# -*- coding: utf-8 -*-
"""Copia de Modulo_1_Filtrado.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14VduWUIYi0EEg3Xf5dcmQv9D8JYRoi81
"""

import numpy as np
import pandas as pd

# ============================================================
# 2) GENERAR UNA SEÑAL DE PROCESO (HUMEDAD) CON RUIDO
# ============================================================
duracion_horas = 3
fs = 1  # 1 dato por segundo
n_muestras = duracion_horas * 60 * 60  # 10800

inicio = "2025-01-01 00:00:00"
tiempo = pd.date_range(start=inicio, periods=n_muestras, freq="S")
t = np.arange(n_muestras)

# Señal base (tendencia lenta + oscilación suave)
humedad_base = 20 + 3 * np.sin(2 * np.pi * t / (60 * 15)) - 0.002 * (t / 60)
humedad_base = np.clip(humedad_base, 8, 30)

# Agregar ruido blanco + picos -> lo que entrega el sensor
np.random.seed(42)
ruido = np.random.normal(loc=0.0, scale=0.8, size=n_muestras)
humedad = humedad_base + ruido

idx_picos = np.random.choice(n_muestras, size=25, replace=False)
humedad[idx_picos] += np.random.choice([5, -5, 8, -8], size=25)

# DataFrame con SOLO la señal medida (puedes agregar más columnas si quieres)
df = pd.DataFrame({"humedad": humedad}, index=tiempo)
df.index.name = "timestamp"

print("Columnas del df:", df.columns.tolist())
print(df.head())

"""#Funcion"""

def filtrado(
    df: pd.DataFrame,
    columna,                    # str o list/tuple de str
    window: int = 5,
    center: bool = False,       # No cambiar porque si no no funciona en tiempo real
    alpha: float = 0.2,
    min_periods: int = 1,
    suffix: str | None = None,
    inplace: bool = False,
):
    """
    Aplica 3 métodos de filtrado (aptos para tiempo real si center=False) sobre una o más columnas
    y retorna 3 DataFrames:
      (df_ma, df_mediana, df_ema)

    Parámetros clave:
    - window, center: rolling mean/median (causal si center=False)
    - alpha: EMA (causal)
    - min_periods: evita NaN al inicio (por defecto 1)
    """

    # Normalizar entrada: str -> [str]
    cols = [columna] if isinstance(columna, str) else list(columna)

    # Validación columnas
    faltantes = [c for c in cols if c not in df.columns]
    if faltantes:
        raise KeyError(f"Estas columnas no existen en el DataFrame: {faltantes}")

    base = df if inplace else df.copy()

    # Validación básica: deben ser numéricas o convertibles
    for c in cols:
        try:
            _ = pd.to_numeric(base[c])
        except Exception as e:
            raise TypeError(f"La columna '{c}' no es numérica ni convertible a numérico.") from e

    # --- 1) Promedio móvil ---
    df_ma = base.copy()
    for c in cols:
        col_ma = f"{c}_ma{window}" if suffix is None else f"{c}_ma{window}_{suffix}"
        df_ma[col_ma] = pd.to_numeric(df_ma[c], errors="coerce").rolling(
            window=window, center=center, min_periods=min_periods
        ).mean()

    # --- 2) Mediana móvil ---
    df_med = base.copy()
    for c in cols:
        col_med = f"{c}_mediana{window}" if suffix is None else f"{c}_mediana{window}_{suffix}"
        df_med[col_med] = pd.to_numeric(df_med[c], errors="coerce").rolling(
            window=window, center=center, min_periods=min_periods
        ).median()

    # --- 3) EMA ---
    df_ema = base.copy()
    alpha_tag = str(alpha).replace(".", "_")
    for c in cols:
        col_ema = f"{c}_ema{alpha_tag}" if suffix is None else f"{c}_ema{alpha_tag}_{suffix}"
        df_ema[col_ema] = pd.to_numeric(df_ema[c], errors="coerce").ewm(
            alpha=alpha, adjust=False
        ).mean()

    return df_ma, df_med, df_ema

import matplotlib.pyplot as plt

# =========================
# Parámetros (ajusta aquí)
# =========================
columna = "humedad"
N = 2000

window = 5
center = False   # TIEMPO REAL: causal (no usar True)
alpha = 0.2
suffix = None    # o "v1", etc.

# =========================
# Ejecutar filtros (3 retornos)
# =========================
df_ma, df_med, df_ema = filtrado(
    df=df,
    columna=columna,
    window=window,
    center=center,
    alpha=alpha,
    suffix=suffix,
    inplace=False
)

# =========================
# Nombres de columnas filtradas (CLAVE)
# =========================
col_ma = f"{columna}_ma{window}" if suffix is None else f"{columna}_ma{window}_{suffix}"
col_med = f"{columna}_mediana{window}" if suffix is None else f"{columna}_mediana{window}_{suffix}"
alpha_tag = str(alpha).replace(".", "_")
col_ema = f"{columna}_ema{alpha_tag}" if suffix is None else f"{columna}_ema{alpha_tag}_{suffix}"

# =========================
# Recortar para graficar
# =========================
N = min(N, len(df))
df_plot     = df.iloc[:N]
df_ma_plot  = df_ma.iloc[:N]
df_med_plot = df_med.iloc[:N]
df_ema_plot = df_ema.iloc[:N]

# --- Gráfico 1: Promedio móvil ---
plt.figure()
plt.plot(df_plot.index, df_plot[columna],
         label=f"{columna} (original)", linewidth=0.8, alpha=0.8)
plt.plot(df_ma_plot.index, df_ma_plot[col_ma],
         label=f"Promedio móvil (window={window}, causal)", linewidth=1.5)
plt.ylabel("Valor")
plt.xlabel("Tiempo")
plt.title(f"Filtro 1: Promedio móvil - {columna}")
plt.grid(True)
plt.legend()
plt.tight_layout()
plt.show()

# --- Gráfico 2: Mediana móvil ---
plt.figure()
plt.plot(df_plot.index, df_plot[columna],
         label=f"{columna} (original)", linewidth=0.8, alpha=0.8)
plt.plot(df_med_plot.index, df_med_plot[col_med],
         label=f"Mediana móvil (window={window}, causal)", linewidth=1.5)
plt.ylabel("Valor")
plt.xlabel("Tiempo")
plt.title(f"Filtro 2: Mediana móvil - {columna}")
plt.grid(True)
plt.legend()
plt.tight_layout()
plt.show()

# --- Gráfico 3: EMA ---
plt.figure()
plt.plot(df_plot.index, df_plot[columna],
         label=f"{columna} (original)", linewidth=0.8, alpha=0.8)
plt.plot(df_ema_plot.index, df_ema_plot[col_ema],
         label=f"EMA (alpha={alpha:.2f}, causal)", linewidth=1.5)
plt.ylabel("Valor")
plt.xlabel("Tiempo")
plt.title(f"Filtro 3: EMA - {columna}")
plt.grid(True)
plt.legend()
plt.tight_layout()
plt.show()

BOL_filtrar_promedio_movil = True
BOL_filtrar_mediana_movil = True
BOL_filtrar_ema = True
BOL_filtrar_butterworth = False

def panel_control(df_input,
                  columna,
                  window,
                  alpha,
                  fc_min,
                  order,
                  N):

    df_local = df_input.copy()
    fc = 1.0 / (fc_min * 60.0)

    print("\n🔎 ESTADO DE FILTROS\n" + "-" * 30)

    filtros = {
        "Promedio móvil": {
            "flag": BOL_filtrar_promedio_movil,
            "col": f"{columna}_ma",
            "func": lambda d: filtrar_promedio_movil(
                d, columna, window=window, center=True, nueva_col=f"{columna}_ma")
        },
        "Mediana móvil": {
            "flag": BOL_filtrar_mediana_movil,
            "col": f"{columna}_mediana",
            "func": lambda d: filtrar_mediana_movil(
                d, columna, window=window, center=True, nueva_col=f"{columna}_mediana")
        },
        "EMA": {
            "flag": BOL_filtrar_ema,
            "col": f"{columna}_ema",
            "func": lambda d: filtrar_ema(
                d, columna, alpha=alpha, nueva_col=f"{columna}_ema")
        },
        "Butterworth": {
            "flag": BOL_filtrar_butterworth,
            "col": f"{columna}_butter",
            "func": lambda d: filtrar_butterworth(
                d, columna, fs=fs, fc=fc, order=order, nueva_col=f"{columna}_butter")
        }
    }

    resultados = {}

    for nombre, cfg in filtros.items():
        if cfg["flag"]:
            print(f"✅ {nombre:15} → ACTIVADO")
            df_local = cfg["func"](df_local)
            resultados[nombre] = df_local[cfg["col"]]
        else:
            print(f"⛔ {nombre:15} → DESACTIVADO")
            resultados[nombre] = None


    # Recorte seguro
    N = min(N, len(df_local))
    df_local = df_local.iloc[:N].copy()

    print("-" * 30)
    print(f"📦 Filas utilizadas: {N}\n")

    return df_local, resultados

def panel_control(
    df_input,
    columna,                    # str o list/tuple de str
    window=5,
    center=False,               # tiempo real (rolling) => causal
    alpha=0.2,
    min_periods=1,
    fc_min=5.0,                 # minutos (Butterworth)
    order=3,
    fs=1.0,
    N=2000,
    suffix=None,
    usar_ma=True,
    usar_mediana=True,
    usar_ema=True,
    usar_butterworth=False,
    verbose=True
):
    """
    Panel de control de filtrado (TODO dentro de esta función).
    Mantiene 4 filtros:
      - Promedio móvil
      - Mediana móvil
      - EMA
      - Butterworth (filtfilt; no causal)

    columna: str o lista/tupla de str
    Retorna: df_ma, df_med, df_ema, df_but (4 DataFrames)
    """

    import numpy as np
    import pandas as pd
    from scipy.signal import butter, filtfilt

    # -------------------------
    # Normalización y validación
    # -------------------------
    cols = [columna] if isinstance(columna, str) else list(columna)

    faltantes = [c for c in cols if c not in df_input.columns]
    if faltantes:
        raise KeyError(f"Estas columnas no existen en el DataFrame: {faltantes}")

    # Recorte seguro (para panel / gráficos)
    N = min(int(N), len(df_input))
    base = df_input.iloc[:N].copy()

    # Validación numérica
    for c in cols:
        try:
            _ = pd.to_numeric(base[c])
        except Exception as e:
            raise TypeError(f"La columna '{c}' no es numérica ni convertible a numérico.") from e

    # -------------------------
    # Nombres de columnas salida
    # -------------------------
    a_tag = str(alpha).replace(".", "_")

    def name_ma(c):   return f"{c}_ma{window}" if suffix is None else f"{c}_ma{window}_{suffix}"
    def name_med(c):  return f"{c}_mediana{window}" if suffix is None else f"{c}_mediana{window}_{suffix}"
    def name_ema(c):  return f"{c}_ema{a_tag}" if suffix is None else f"{c}_ema{a_tag}_{suffix}"
    def name_but(c):  return f"{c}_butter" if suffix is None else f"{c}_butter_{suffix}"

    # -------------------------
    # Definición interna de filtros (diccionario)
    # -------------------------
    fc = 1.0 / (float(fc_min) * 60.0)  # Hz desde minutos

    filtros = {
        "Promedio móvil": {
            "flag": usar_ma,
            "key": "ma",
            "apply": lambda d, c: d.assign(**{
                name_ma(c): pd.to_numeric(d[c], errors="coerce").rolling(
                    window=window, center=center, min_periods=min_periods
                ).mean()
            }),
        },
        "Mediana móvil": {
            "flag": usar_mediana,
            "key": "med",
            "apply": lambda d, c: d.assign(**{
                name_med(c): pd.to_numeric(d[c], errors="coerce").rolling(
                    window=window, center=center, min_periods=min_periods
                ).median()
            }),
        },
        "EMA": {
            "flag": usar_ema,
            "key": "ema",
            "apply": lambda d, c: d.assign(**{
                name_ema(c): pd.to_numeric(d[c], errors="coerce").ewm(
                    alpha=alpha, adjust=False
                ).mean()
            }),
        },
        "Butterworth": {
            "flag": usar_butterworth,
            "key": "but",
            "apply": None,  # se calcula abajo por requerir validaciones extra
        },
    }

    # -------------------------
    # Inicializar salidas (si filtro desactivado, queda base)
    # -------------------------
    out = {
        "ma": base.copy(),
        "med": base.copy(),
        "ema": base.copy(),
        "but": base.copy(),
    }

    if verbose:
        print("\nESTADO DE FILTROS\n" + "-" * 30)

    # -------------------------
    # Aplicar MA / Mediana / EMA (vectorizado por assign)
    # -------------------------
    for nombre in ["Promedio móvil", "Mediana móvil", "EMA"]:
        cfg = filtros[nombre]
        if verbose:
            print(("ACTIVADO   - " if cfg["flag"] else "DESACTIVADO- ") + nombre)

        if cfg["flag"]:
            dtemp = base.copy()
            for c in cols:
                dtemp = cfg["apply"](dtemp, c)
            out[cfg["key"]] = dtemp

    # -------------------------
    # Aplicar Butterworth (si está activado)
    # -------------------------
    cfg_b = filtros["Butterworth"]
    if verbose:
        print(("ACTIVADO   - " if cfg_b["flag"] else "DESACTIVADO- ") + "Butterworth")

    if cfg_b["flag"]:
        # Validar frecuencia normalizada
        w_norm = fc / (fs / 2)
        if not (0 < w_norm < 1):
            raise ValueError(f"Frecuencia normalizada inválida: w_norm={w_norm:.6g}. Revisa fs y fc_min.")

        b, a = butter(order, w_norm, btype="low", analog=False)

        padlen = 3 * (max(len(a), len(b)) - 1)
        if len(base) <= padlen:
            raise ValueError(
                f"Serie demasiado corta para filtfilt con order={order}. "
                f"len={len(base)}, padlen={padlen}. Baja order o usa más datos."
            )

        dtemp = base.copy()
        for c in cols:
            x = pd.to_numeric(dtemp[c], errors="coerce").astype(float)
            if x.isna().all():
                raise ValueError(f"La columna '{c}' es todo NaN tras convertir a numérico.")

            # filtfilt no tolera NaN: interpolar SOLO para Butterworth
            if isinstance(dtemp.index, pd.DatetimeIndex):
                x_i = x.interpolate(method="time")
            else:
                x_i = x.interpolate()
            x_i = x_i.ffill().bfill()

            dtemp[name_but(c)] = filtfilt(b, a, x_i.to_numpy())

        out["but"] = dtemp

    if verbose:
        print("-" * 30)
        print(f"Filas utilizadas: {N}\n")

    return out["ma"], out["med"], out["ema"], out["but"]

# =========================
# FLAGS (DEBEN ESTAR AFUERA)
# =========================
BOL_filtrar_promedio_movil = True
BOL_filtrar_mediana_movil  = True
BOL_filtrar_ema            = True
BOL_filtrar_butterworth    = False


def panel_control(
    df_input,
    columna,                    # str o list/tuple de str
    window=5,
    center=False,               # rolling causal
    alpha=0.2,
    min_periods=1,
    fc_min=5.0,                 # minutos (Butterworth)
    order=3,
    fs=1.0,
    N=2000,
    suffix=None,
    verbose=True
):
    """
    Panel de control de filtrado (TODO dentro de esta función).
    Mantiene 4 filtros:
      - Promedio móvil
      - Mediana móvil
      - EMA
      - Butterworth (filtfilt; no causal)

    La activación de filtros se controla con FLAGS definidos afuera:
      BOL_filtrar_promedio_movil, BOL_filtrar_mediana_movil,
      BOL_filtrar_ema, BOL_filtrar_butterworth

    Retorna: df_ma, df_med, df_ema, df_but (4 DataFrames)
    """

    import pandas as pd
    from scipy.signal import butter, filtfilt

    # -------------------------
    # Normalización y validación
    # -------------------------
    cols = [columna] if isinstance(columna, str) else list(columna)

    faltantes = [c for c in cols if c not in df_input.columns]
    if faltantes:
        raise KeyError(f"Estas columnas no existen en el DataFrame: {faltantes}")

    # Recorte seguro (para panel / gráficos)
    N = min(int(N), len(df_input))
    base = df_input.iloc[:N].copy()

    # Validación numérica
    for c in cols:
        try:
            _ = pd.to_numeric(base[c])
        except Exception as e:
            raise TypeError(f"La columna '{c}' no es numérica ni convertible a numérico.") from e

    # -------------------------
    # Nombres de columnas salida
    # -------------------------
    a_tag = str(alpha).replace(".", "_")

    def name_ma(c):   return f"{c}_ma{window}" if suffix is None else f"{c}_ma{window}_{suffix}"
    def name_med(c):  return f"{c}_mediana{window}" if suffix is None else f"{c}_mediana{window}_{suffix}"
    def name_ema(c):  return f"{c}_ema{a_tag}" if suffix is None else f"{c}_ema{a_tag}_{suffix}"
    def name_but(c):  return f"{c}_butter" if suffix is None else f"{c}_butter_{suffix}"

    # -------------------------
    # Definición interna de filtros (diccionario)
    # -------------------------
    fc = 1.0 / (float(fc_min) * 60.0)  # Hz desde minutos

    filtros = {
        "Promedio móvil": {
            "flag": BOL_filtrar_promedio_movil,
            "key": "ma",
            "apply": lambda d, c: d.assign(**{
                name_ma(c): pd.to_numeric(d[c], errors="coerce").rolling(
                    window=window, center=center, min_periods=min_periods
                ).mean()
            }),
        },
        "Mediana móvil": {
            "flag": BOL_filtrar_mediana_movil,
            "key": "med",
            "apply": lambda d, c: d.assign(**{
                name_med(c): pd.to_numeric(d[c], errors="coerce").rolling(
                    window=window, center=center, min_periods=min_periods
                ).median()
            }),
        },
        "EMA": {
            "flag": BOL_filtrar_ema,
            "key": "ema",
            "apply": lambda d, c: d.assign(**{
                name_ema(c): pd.to_numeric(d[c], errors="coerce").ewm(
                    alpha=alpha, adjust=False
                ).mean()
            }),
        },
        "Butterworth": {
            "flag": BOL_filtrar_butterworth,
            "key": "but",
            "apply": None,  # se calcula abajo por requerir validaciones extra
        },
    }

    # -------------------------
    # Inicializar salidas (si filtro desactivado, queda base)
    # -------------------------
    out = {
        "ma": base.copy(),
        "med": base.copy(),
        "ema": base.copy(),
        "but": base.copy(),
    }

    if verbose:
        print("\nESTADO DE FILTROS\n" + "-" * 30)

    # -------------------------
    # Aplicar MA / Mediana / EMA
    # -------------------------
    for nombre in ["Promedio móvil", "Mediana móvil", "EMA"]:
        cfg = filtros[nombre]
        if verbose:
            print(("ACTIVADO   - " if cfg["flag"] else "DESACTIVADO- ") + nombre)

        if cfg["flag"]:
            dtemp = base.copy()
            for c in cols:
                dtemp = cfg["apply"](dtemp, c)
            out[cfg["key"]] = dtemp

    # -------------------------
    # Aplicar Butterworth (si está activado)
    # -------------------------
    cfg_b = filtros["Butterworth"]
    if verbose:
        print(("ACTIVADO   - " if cfg_b["flag"] else "DESACTIVADO- ") + "Butterworth")

    if cfg_b["flag"]:
        w_norm = fc / (fs / 2)
        if not (0 < w_norm < 1):
            raise ValueError(f"Frecuencia normalizada inválida: w_norm={w_norm:.6g}. Revisa fs y fc_min.")

        b, a = butter(order, w_norm, btype="low", analog=False)

        padlen = 3 * (max(len(a), len(b)) - 1)
        if len(base) <= padlen:
            raise ValueError(
                f"Serie demasiado corta para filtfilt con order={order}. "
                f"len={len(base)}, padlen={padlen}. Baja order o usa más datos."
            )

        dtemp = base.copy()
        for c in cols:
            x = pd.to_numeric(dtemp[c], errors="coerce").astype(float)
            if x.isna().all():
                raise ValueError(f"La columna '{c}' es todo NaN tras convertir a numérico.")

            if isinstance(dtemp.index, pd.DatetimeIndex):
                x_i = x.interpolate(method="time")
            else:
                x_i = x.interpolate()
            x_i = x_i.ffill().bfill()

            dtemp[name_but(c)] = filtfilt(b, a, x_i.to_numpy())

        out["but"] = dtemp

    if verbose:
        print("-" * 30)
        print(f"Filas utilizadas: {N}\n")

    return out["ma"], out["med"], out["ema"], out["but"]

import matplotlib.pyplot as plt

# =========================
# Parámetros (ajusta aquí)
# =========================
columna = "humedad"          # puede ser "humedad" o ["humedad","otra_col"]
N = 2000

window = 5
center = False              # rolling causal
alpha = 0.2
min_periods = 1
suffix = None

# Butterworth (para graficar los 4, debe estar activado)
fc_min = 5.0                # minutos
order = 3
fs = 1.0

# =========================
# Ejecutar panel (4 retornos)
# =========================
df_ma, df_med, df_ema, df_but = panel_control(
    df_input=df,
    columna=columna,
    window=window,
    center=center,
    alpha=alpha,
    min_periods=min_periods,
    fc_min=fc_min,
    order=order,
    fs=fs,
    N=N,
    suffix=suffix,
    usar_ma=True,
    usar_mediana=True,
    usar_ema=True,
    usar_butterworth=True,   # <- ACTIVADO para graficar los 4
    verbose=True
)

# =========================
# Normalizar columna a lista
# =========================
cols = [columna] if isinstance(columna, str) else list(columna)

# =========================
# Nombres de columnas filtradas
# =========================
alpha_tag = str(alpha).replace(".", "_")

def col_ma_name(c):  return f"{c}_ma{window}" if suffix is None else f"{c}_ma{window}_{suffix}"
def col_med_name(c): return f"{c}_mediana{window}" if suffix is None else f"{c}_mediana{window}_{suffix}"
def col_ema_name(c): return f"{c}_ema{alpha_tag}" if suffix is None else f"{c}_ema{alpha_tag}_{suffix}"
def col_but_name(c): return f"{c}_butter" if suffix is None else f"{c}_butter_{suffix}"

# =========================
# Recortar (por seguridad)
# =========================
N = min(N, len(df))
df_plot     = df.iloc[:N]
df_ma_plot  = df_ma.iloc[:N]
df_med_plot = df_med.iloc[:N]
df_ema_plot = df_ema.iloc[:N]
df_but_plot = df_but.iloc[:N]

# =========================
# Graficar 4 filtros por variable
# =========================
for c in cols:

    # --- Gráfico 1: Promedio móvil ---
    plt.figure()
    plt.plot(df_plot.index, df_plot[c], label=f"{c} (original)", linewidth=0.8, alpha=0.8)
    plt.plot(df_ma_plot.index, df_ma_plot[col_ma_name(c)], label=f"Promedio móvil (window={window}, causal)", linewidth=1.5)
    plt.ylabel("Valor"); plt.xlabel("Tiempo")
    plt.title(f"Filtro 1: Promedio móvil - {c}")
    plt.grid(True); plt.legend(); plt.tight_layout(); plt.show()

    # --- Gráfico 2: Mediana móvil ---
    plt.figure()
    plt.plot(df_plot.index, df_plot[c], label=f"{c} (original)", linewidth=0.8, alpha=0.8)
    plt.plot(df_med_plot.index, df_med_plot[col_med_name(c)], label=f"Mediana móvil (window={window}, causal)", linewidth=1.5)
    plt.ylabel("Valor"); plt.xlabel("Tiempo")
    plt.title(f"Filtro 2: Mediana móvil - {c}")
    plt.grid(True); plt.legend(); plt.tight_layout(); plt.show()

    # --- Gráfico 3: EMA ---
    plt.figure()
    plt.plot(df_plot.index, df_plot[c], label=f"{c} (original)", linewidth=0.8, alpha=0.8)
    plt.plot(df_ema_plot.index, df_ema_plot[col_ema_name(c)], label=f"EMA (alpha={alpha:.2f}, causal)", linewidth=1.5)
    plt.ylabel("Valor"); plt.xlabel("Tiempo")
    plt.title(f"Filtro 3: EMA - {c}")
    plt.grid(True); plt.legend(); plt.tight_layout(); plt.show()

    # --- Gráfico 4: Butterworth ---
    plt.figure()
    plt.plot(df_plot.index, df_plot[c], label=f"{c} (original)", linewidth=0.8, alpha=0.8)
    plt.plot(df_but_plot.index, df_but_plot[col_but_name(c)], label=f"Butterworth (fc={fc_min} min, orden={order})", linewidth=1.5)
    plt.ylabel("Valor"); plt.xlabel("Tiempo")
    plt.title(f"Filtro 4: Butterworth - {c}")
    plt.grid(True); plt.legend(); plt.tight_layout(); plt.show()

import matplotlib.pyplot as plt

# =========================
# Parámetros (ajusta aquí)
# =========================
columna = "humedad"          # puede ser "humedad" o ["humedad","otra_col"]
N = 2000

window = 5
center = False              # rolling causal
alpha = 0.2
min_periods = 1
suffix = None

# Butterworth
fc_min = 5.0                # minutos
order = 3
fs = 1.0

# =========================
# Ejecutar panel (4 retornos)
# =========================
df_ma, df_med, df_ema, df_but = panel_control(
    df_input=df,
    columna=columna,
    window=window,
    center=center,
    alpha=alpha,
    min_periods=min_periods,
    fc_min=fc_min,
    order=order,
    fs=fs,
    N=N,
    suffix=suffix,
    verbose=True
)

# =========================
# Normalizar columna a lista
# =========================
cols = [columna] if isinstance(columna, str) else list(columna)

# =========================
# Nombres de columnas filtradas
# =========================
alpha_tag = str(alpha).replace(".", "_")

def col_ma_name(c):  return f"{c}_ma{window}" if suffix is None else f"{c}_ma{window}_{suffix}"
def col_med_name(c): return f"{c}_mediana{window}" if suffix is None else f"{c}_mediana{window}_{suffix}"
def col_ema_name(c): return f"{c}_ema{alpha_tag}" if suffix is None else f"{c}_ema{alpha_tag}_{suffix}"
def col_but_name(c): return f"{c}_butter" if suffix is None else f"{c}_butter_{suffix}"

# =========================
# Recortar (solo si existe el df)
# =========================
N = min(N, len(df))
df_plot = df.iloc[:N]

df_ma_plot  = None if df_ma  is None else df_ma.iloc[:N]
df_med_plot = None if df_med is None else df_med.iloc[:N]
df_ema_plot = None if df_ema is None else df_ema.iloc[:N]
df_but_plot = None if df_but is None else df_but.iloc[:N]

# =========================
# Graficar por variable
# =========================
for c in cols:

    # --- Gráfico 1: Promedio móvil ---
    if df_ma_plot is not None:
        plt.figure()
        plt.plot(df_plot.index, df_plot[c], label=f"{c} (original)", linewidth=0.8, alpha=0.8)
        plt.plot(df_ma_plot.index, df_ma_plot[col_ma_name(c)], label=f"Promedio móvil (window={window}, causal)", linewidth=1.5)
        plt.ylabel("Valor"); plt.xlabel("Tiempo")
        plt.title(f"Filtro 1: Promedio móvil - {c}")
        plt.grid(True); plt.legend(); plt.tight_layout(); plt.show()

    # --- Gráfico 2: Mediana móvil ---
    if df_med_plot is not None:
        plt.figure()
        plt.plot(df_plot.index, df_plot[c], label=f"{c} (original)", linewidth=0.8, alpha=0.8)
        plt.plot(df_med_plot.index, df_med_plot[col_med_name(c)], label=f"Mediana móvil (window={window}, causal)", linewidth=1.5)
        plt.ylabel("Valor"); plt.xlabel("Tiempo")
        plt.title(f"Filtro 2: Mediana móvil - {c}")
        plt.grid(True); plt.legend(); plt.tight_layout(); plt.show()

    # --- Gráfico 3: EMA ---
    if df_ema_plot is not None:
        plt.figure()
        plt.plot(df_plot.index, df_plot[c], label=f"{c} (original)", linewidth=0.8, alpha=0.8)
        plt.plot(df_ema_plot.index, df_ema_plot[col_ema_name(c)], label=f"EMA (alpha={alpha:.2f}, causal)", linewidth=1.5)
        plt.ylabel("Valor"); plt.xlabel("Tiempo")
        plt.title(f"Filtro 3: EMA - {c}")
        plt.grid(True); plt.legend(); plt.tight_layout(); plt.show()

    # --- Gráfico 4: Butterworth ---
    if df_but_plot is not None:
        plt.figure()
        plt.plot(df_plot.index, df_plot[c], label=f"{c} (original)", linewidth=0.8, alpha=0.8)
        plt.plot(df_but_plot.index, df_but_plot[col_but_name(c)], label=f"Butterworth (fc={fc_min} min, orden={order})", linewidth=1.5)
        plt.ylabel("Valor"); plt.xlabel("Tiempo")
        plt.title(f"Filtro 4: Butterworth - {c}")
        plt.grid(True); plt.legend(); plt.tight_layout(); plt.show()