# -*- coding: utf-8 -*-
"""Experto_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zuprW0BdXC_zZvANZ3KJBmlew4dvsQAa

#Librerias
"""

# -*- coding: utf-8 -*-
"""Modulo_2_Fuzzy.5.ipynb (actualizado: Pendiente por variable + Sugeno)"""

import seaborn as sns
import pandas as pd
import numpy as np
import time
import matplotlib.pyplot as plt
import datetime

"""#Funciones fuzzy"""

"""#Funciones fuzzy"""

def crear_clase_fuzzy_Low(nombre_clase, offset, **conjuntos):
    class FuzzyTemplate:
        def __init__(self):
            self.offset = np.array(offset, dtype=float)
            for nombre, valores in conjuntos.items():
                setattr(self, nombre, np.array(valores, dtype=float))
            for nombre in conjuntos.keys():
                vector = getattr(self, nombre)
                setattr(
                    self,
                    f"mf_{nombre}",
                    lambda x, v=vector: np.interp(x, self.offset, v, left=v[0], right=v[-1])
                )

        def calcular_offset(self, pv, lmin):
            return float(pv) - float(lmin)

        def evaluar(self, pv, lmin):
            off = self.calcular_offset(pv, lmin)
            pertenencias = {}
            for nombre in conjuntos.keys():
                mf = getattr(self, f"mf_{nombre}")
                pertenencias[nombre] = float(np.clip(mf(off), 0, 1))
            dominante = max(pertenencias, key=pertenencias.get)
            val_dom = pertenencias[dominante]
            return dominante, val_dom, off, pertenencias

    FuzzyTemplate.__name__ = nombre_clase
    return FuzzyTemplate


def crear_clase_fuzzy_high(nombre_clase, offset, **conjuntos):
    class FuzzyTemplate:
        def __init__(self):
            self.offset = np.array(offset, dtype=float)
            for nombre, valores in conjuntos.items():
                setattr(self, nombre, np.array(valores, dtype=float))
            for nombre in conjuntos.keys():
                vector = getattr(self, nombre)
                setattr(
                    self,
                    f"mf_{nombre}",
                    lambda x, v=vector: np.interp(x, self.offset, v, left=v[0], right=v[-1])
                )

        def calcular_offset(self, pv, lmax):
            return float(lmax) - float(pv)

        def evaluar(self, pv, lmax):
            off = self.calcular_offset(pv, lmax)
            pertenencias = {}
            for nombre in conjuntos.keys():
                mf = getattr(self, f"mf_{nombre}")
                pertenencias[nombre] = float(np.clip(mf(off), 0, 1))
            dominante = max(pertenencias, key=pertenencias.get)
            val_dom = pertenencias[dominante]
            return dominante, val_dom, off, pertenencias

    FuzzyTemplate.__name__ = nombre_clase
    return FuzzyTemplate


def crear_clase_fuzzy_norm(nombre_clase, offset, **conjuntos):
    class FuzzyTemplate:
        def __init__(self):
            self.offset = np.array(offset, dtype=float)
            for nombre, valores in conjuntos.items():
                setattr(self, nombre, np.array(valores, dtype=float))
            for nombre in conjuntos.keys():
                vector = getattr(self, nombre)
                setattr(
                    self,
                    f"mf_{nombre}",
                    lambda x, v=vector: np.interp(x, self.offset, v, left=v[0], right=v[-1])
                )

        def calcular_offset(self, pv, lmin, lmax):
            den = (float(lmax) - float(lmin))
            if abs(den) < 1e-12:
                return 0.5
            return (float(pv) - float(lmin)) / den

        def evaluar(self, pv, lmin, lmax):
            off = self.calcular_offset(pv, lmin, lmax)
            pertenencias = {}
            for nombre in conjuntos.keys():
                mf = getattr(self, f"mf_{nombre}")
                pertenencias[nombre] = float(np.clip(mf(off), 0, 1))
            dominante = max(pertenencias, key=pertenencias.get)
            val_dom = pertenencias[dominante]
            return dominante, val_dom, off, pertenencias

    FuzzyTemplate.__name__ = nombre_clase
    return FuzzyTemplate


def crear_clase_fuzzy_pendiente(nombre_clase, x, **conjuntos):
    class FuzzyPendienteTemplate:
        def __init__(self):
            self.x = np.array(x, dtype=float)
            for nombre, valores in conjuntos.items():
                setattr(self, nombre, np.array(valores, dtype=float))
            for nombre in conjuntos.keys():
                vector = getattr(self, nombre)
                setattr(
                    self,
                    f"mf_{nombre}",
                    lambda p, v=vector: np.interp(p, self.x, v, left=v[0], right=v[-1])
                )

        def evaluar(self, pendiente):
            p = float(pendiente)
            pertenencias = {}
            for nombre in conjuntos.keys():
                mf = getattr(self, f"mf_{nombre}")
                pertenencias[nombre] = float(np.clip(mf(p), 0, 1))
            dominante = max(pertenencias, key=pertenencias.get)
            inferencia = pertenencias[dominante]
            return dominante, p, pertenencias, inferencia

    FuzzyPendienteTemplate.__name__ = nombre_clase
    return FuzzyPendienteTemplate


def crear_clase_fuzzy_varianza(nombre_clase, x, **conjuntos):
    """
    Template fuzzy para varianza (σ²).

    Parámetros
    ----------
    nombre_clase : str
        Nombre de la clase generada.
    x : list/array
        Eje de varianza (σ²) donde defines las MFs. Debe ser creciente.
    **conjuntos : dict[str, list/array]
        Conjuntos difusos discretizados sobre x.
        Ej: baja=[...], media=[...], alta=[...]

    Retorna
    -------
    Clase instanciable con:
      - self.x
      - self.<conjunto>
      - self.mf_<conjunto>(v)
      - evaluar(varianza) -> (dominante, v, pertenencias, inferencia)
    """
    class FuzzyVarianzaTemplate:
        def __init__(self):
            self.x = np.array(x, dtype=float)

            # guardar vectores de cada conjunto
            for nombre, valores in conjuntos.items():
                setattr(self, nombre, np.array(valores, dtype=float))

            # crear interpoladores (membership functions)
            for nombre in conjuntos.keys():
                vector = getattr(self, nombre)
                setattr(
                    self,
                    f"mf_{nombre}",
                    lambda v, vec=vector: np.interp(v, self.x, vec, left=vec[0], right=vec[-1])
                )

        def evaluar(self, varianza):
            v = float(varianza)

            pertenencias = {}
            for nombre in conjuntos.keys():
                mf = getattr(self, f"mf_{nombre}")
                pertenencias[nombre] = float(np.clip(mf(v), 0, 1))

            dominante = max(pertenencias, key=pertenencias.get)
            inferencia = pertenencias[dominante]
            return dominante, v, pertenencias, inferencia

    FuzzyVarianzaTemplate.__name__ = nombre_clase
    return FuzzyVarianzaTemplate

"""#Fuzzy"""

# ----------------------------
# FUZZY SETS (actualizados)
# - Se agregan conjuntos: cerca_alto y cerca_bajo
# - Mantiene tu mismo formato y offsets
# ----------------------------

# ----------------------------
# Potencia Bolas (Low offset, respecto a lmin)
# offset = pv - lmin
# ----------------------------
PotMolBolas = crear_clase_fuzzy_Low(
    "pot_mol_bolas",
    offset=[-10, 0, 10, 20, 40, 60, 70, 80],
    bajo=[0, 0, 0, 0.5, 1, 1, 1, 1],
    OK=[0, 0.5, 1, 0.5, 0, 0, 0, 0],
    alto=[1, 0.5, 0, 0, 0, 0, 0, 0],
    cerca_alto=[0.5, 1, 0.5, 0, 0, 0, 0, 0],
    cerca_bajo=[0, 0, 0.5, 1, 0.5, 0, 0, 0],
)
fuzzy_pot_bolas = PotMolBolas()

# ----------------------------
# Potencia SAG (High offset, respecto a lmax)
# offset = lmax - pv
# ----------------------------
PotSag1 = crear_clase_fuzzy_high(
    "pot_sag1",
    offset=[-10, 0, 10, 20, 40, 60, 70, 80],
    bajo=[0, 0, 0, 0.5, 1, 1, 1, 1],
    OK=[0, 0.5, 1, 0.5, 0, 0, 0, 0],
    alto=[1, 0.5, 0, 0, 0, 0, 0, 0],
    cerca_alto=[0.5, 1, 0.5, 0, 0, 0, 0, 0],
    cerca_bajo=[0, 0, 0.5, 1, 0.5, 0, 0, 0],
)
fuzzy_pot_sag1 = PotSag1()

# ----------------------------
# Nivel (NORMALIZADO) offset ~ [0..1]
# offset = (pv - lmin) / (lmax - lmin)
# ----------------------------
FuzzyNivel1 = crear_clase_fuzzy_norm(
    "fuzzy_nivel1",
    offset=[0.0, 0.2, 0.4, 0.5, 0.6, 0.8, 1.0],
    bajo=[1, 1, 0.5, 0, 0, 0, 0],
    OK=[0, 0.2, 0.8, 1, 0.8, 0.2, 0],
    alto=[0, 0, 0, 0, 0.5, 1, 1],
    cerca_bajo=[0, 1, 0.6, 0.1, 0, 0, 0],
    cerca_alto=[0, 0, 0, 0.1, 0.6, 1, 0.5],
)
fuzzy_nivel1 = FuzzyNivel1()

# ----------------------------
# P80 (High offset vs lmax)
# offset = lmax - pv
# ----------------------------
P80Model = crear_clase_fuzzy_high(
    "p80_model",
    offset=[-20, 0, 20, 40, 60, 80, 100, 120],
    bajo=[0, 0, 0, 0.5, 1, 1, 1, 1],
    OK=[0, 0.5, 1, 0.5, 0, 0, 0, 0],
    alto=[1, 0.5, 0, 0, 0, 0, 0, 0],
    cerca_alto=[0.5, 1, 0.5, 0, 0, 0, 0, 0],
    cerca_bajo=[0, 0, 0.5, 1, 0.5, 0, 0, 0],
)
fuzzy_p80 = P80Model()

# ----------------------------
# Presión (High offset vs lmax)
# offset = lmax - pv
# ----------------------------
PresionModel = crear_clase_fuzzy_high(
    "presion_model",
    offset=[-5, 0, 5, 10, 20, 30, 40, 50],
    bajo=[0, 0, 0, 0.5, 1, 1, 1, 1],
    OK=[0, 0.5, 1, 0.5, 0, 0, 0, 0],
    alto=[1, 0.5, 0, 0, 0, 0, 0, 0],
    cerca_alto=[0.5, 1, 0.5, 0, 0, 0, 0, 0],
    cerca_bajo=[0, 0, 0.5, 1, 0.5, 0, 0, 0],
)
fuzzy_presion = PresionModel()

# ----------------------------
# Densidad (High offset vs lmax)
# offset = lmax - pv
# ----------------------------
DensidadModel = crear_clase_fuzzy_high(
    "densidad_model",
    offset=[-10, 0, 10, 20, 30, 40, 50, 60],
    bajo=[0, 0, 0, 0.5, 1, 1, 1, 1],
    OK=[0, 0.5, 1, 0.5, 0, 0, 0, 0],
    alto=[1, 0.5, 0, 0, 0, 0, 0, 0],
    cerca_alto=[0.5, 1, 0.5, 0, 0, 0, 0, 0],
    cerca_bajo=[0, 0, 0.5, 1, 0.5, 0, 0, 0],
)
fuzzy_densidad = DensidadModel()

"""#Fuzzy pendiente"""

"""#Fuzzy pendiente (3 estados y por variable)"""

# Membresías 3-estados (sobre 7 puntos)
BAJANDO_3 = [1, 1, 0.5, 0, 0, 0, 0]
ESTABLE_3 = [0, 0, 0.5, 1, 0.5, 0, 0]
SUBIENDO_3 = [0, 0, 0, 0, 0.5, 1, 1]

# ----------------------------
# CONFIG EDITABLE POR VARIABLE
# - x está en unidades de "delta por minuto" de ESA VARIABLE.
# - Para agregar variables: solo añade una entrada aquí y a PEND_MODELOS si quieres.
# ----------------------------
PENDIENTE_CFG = {
    # pot_sag en tu simulación está ~ 16..26 => pendiente típica pequeña
    "pot_sag":   {"x": [-1.5, -0.8, -0.3, 0, 0.3, 0.8, 1.5], "unit": "u/min"},
    # pot_bolas ~ 700..770 => pendiente mayor
    "pot_bolas": {"x": [-30, -15, -5, 0, 5, 15, 30],        "unit": "u/min"},
    # nivel ~ 45..80 => pendiente moderada (en tu simulación)
    "nivel":     {"x": [-6, -3, -1, 0, 1, 3, 6],            "unit": "u/min"},
    # p80 ~ 100..350
    "p80":       {"x": [-30, -15, -5, 0, 5, 15, 30],        "unit": "u/min"},
    # presion ~ 5..25
    "presion":   {"x": [-3, -1.5, -0.6, 0, 0.6, 1.5, 3],    "unit": "u/min"},
    # densidad ~ 1.20..1.60
    "densidad":  {"x": [-0.08, -0.04, -0.015, 0, 0.015, 0.04, 0.08], "unit": "u/min"},
}

def crear_pendiente_por_variable(nombre_var):
    if nombre_var not in PENDIENTE_CFG:
        raise KeyError(
            f"No existe configuración de pendiente para '{nombre_var}'. "
            f"Agrega PENDIENTE_CFG['{nombre_var}'] = {{'x':[...], 'unit':'u/min'}}"
        )
    x = PENDIENTE_CFG[nombre_var]["x"]
    Pend = crear_clase_fuzzy_pendiente(
        f"pend_{nombre_var}",
        x=x,
        BAJANDO=BAJANDO_3,
        ESTABLE=ESTABLE_3,
        SUBIENDO=SUBIENDO_3
    )
    return Pend()

# Construcción modelos (mantengo tu formato)
pend_pot_bolas = crear_pendiente_por_variable("pot_bolas")
pend_pot_sag   = crear_pendiente_por_variable("pot_sag")
pend_nivel     = crear_pendiente_por_variable("nivel")
pend_p80       = crear_pendiente_por_variable("p80")
pend_presion   = crear_pendiente_por_variable("presion")
pend_densidad  = crear_pendiente_por_variable("densidad")

PEND_MODELOS = {
    "pot_bolas": pend_pot_bolas,
    "pot_sag": pend_pot_sag,
    "nivel": pend_nivel,
    "p80": pend_p80,
    "presion": pend_presion,
    "densidad": pend_densidad
}


def evaluar_pendiente_var(var_name, pv, t_s, hist, dt_min_floor=1e-6):
    """
    Devuelve:
      dom ∈ {SUBIENDO, ESTABLE, BAJANDO}
      pert = {SUBIENDO, ESTABLE, BAJANDO}
      belief NO se calcula aquí; belief = fuerza_regla del motor.
    """
    modelo = PEND_MODELOS[var_name]
    prev = hist.get(var_name)

    if prev is None:
        slope_per_min = 0.0
    else:
        t_prev, pv_prev = prev
        dt_min = max((t_s - t_prev) / 60.0, dt_min_floor)
        slope_per_min = (float(pv) - float(pv_prev)) / dt_min

    dom_raw, p, pert_raw, inf = modelo.evaluar(slope_per_min)

    # normalizar
    pert = {str(k).upper(): float(v) for k, v in pert_raw.items()}
    dom = str(dom_raw).upper()

    hist[var_name] = (float(t_s), float(pv))

    return {
        "dom": dom,
        "val": float(pert.get(dom, inf)),
        "offset": float(slope_per_min),
        "pert": pert,
        "slope_per_min": float(slope_per_min),
    }

"""#Modelos difusos"""

"""#Modelos difusos"""

def _upper_keys(d):
    return {str(k).upper(): float(v) for k, v in (d or {}).items()}

def _upper_dom(s):
    return str(s).strip().upper()

def evaluar_fuzzy(
    pv_bolas, lmin_bolas,
    pv_sag, lmax_sag,
    pv_nivel, lmin_nivel, lmax_nivel,
    pv_p80, lmax_p80,
    pv_pres, lmax_pres,
    pv_dens, lmax_dens,
):
    dom_bolas, val_bolas, off_bolas, pert_bolas = fuzzy_pot_bolas.evaluar(pv_bolas, lmin_bolas)
    dom_sag,   val_sag,   off_sag,   pert_sag   = fuzzy_pot_sag1.evaluar(pv_sag, lmax_sag)
    dom_nivel, val_nivel, off_nivel, pert_nivel = fuzzy_nivel1.evaluar(pv_nivel, lmin_nivel, lmax_nivel)
    dom_p80,   val_p80,   off_p80,   pert_p80   = fuzzy_p80.evaluar(pv_p80, lmax_p80)
    dom_pres,  val_pres,  off_pres,  pert_pres  = fuzzy_presion.evaluar(pv_pres, lmax_pres)
    dom_dens,  val_dens,  off_dens,  pert_dens  = fuzzy_densidad.evaluar(pv_dens, lmax_dens)

    return {
        "pot_bolas": {"dom": _upper_dom(dom_bolas), "val": float(val_bolas), "offset": float(off_bolas), "pert": _upper_keys(pert_bolas)},
        "pot_sag":   {"dom": _upper_dom(dom_sag),   "val": float(val_sag),   "offset": float(off_sag),   "pert": _upper_keys(pert_sag)},
        "nivel":     {"dom": _upper_dom(dom_nivel), "val": float(val_nivel), "offset": float(off_nivel), "pert": _upper_keys(pert_nivel)},
        "p80":       {"dom": _upper_dom(dom_p80),   "val": float(val_p80),   "offset": float(off_p80),   "pert": _upper_keys(pert_p80)},
        "presion":   {"dom": _upper_dom(dom_pres),  "val": float(val_pres),  "offset": float(off_pres),  "pert": _upper_keys(pert_pres)},
        "densidad":  {"dom": _upper_dom(dom_dens),  "val": float(val_dens),  "offset": float(off_dens),  "pert": _upper_keys(pert_dens)},
    }

"""#Reglas"""

# Acciones por regla deben ser LISTAS (para acciones compuestas)
REGLAS = {
    "molino_cargado": [],
    "cajon_alto": [],
    "p80_alto": [],
    "optimizar_potencia": [],
    "p80_no_alto": [],
    "densidad_presion": [],
    "presion": []
}

# BLOQUE 1 — Molino cargado (1–4)
REGLAS["molino_cargado"] += [
    {   # 1
        "id": 1,
        "descripcion": "Potencia Molino ALTO y NO-BAJANDO; Nivel NO-ALTO; P80 NO-ALTO",
        "si": [("pot_sag","ALTO"), ("pot_sag_tend","NO-BAJANDO"), ("nivel","NO-ALTO"), ("p80","NO-ALTO")],
        "acciones": ["aumentar_agua_molino", "disminuir_agua_cajon"],
        "duracion": 60,
        "prioridad": 1
    },
    {   # 2
        "id": 2,
        "descripcion": "Potencia Molino ALTO y NO-BAJANDO; Nivel NO-ALTO; P80 ALTO",
        "si": [("pot_sag","ALTO"), ("pot_sag_tend","NO-BAJANDO"), ("nivel","NO-ALTO"), ("p80","ALTO")],
        "acciones": ["disminuir_tonelaje"],
        "duracion": 90,
        "prioridad": 1
    },
    {   # 3
        "id": 3,
        "descripcion": "Potencia Molino ALTO y NO-BAJANDO; Nivel ALTO; P80 NO-ALTO",
        "si": [("pot_sag","ALTO"), ("pot_sag_tend","NO-BAJANDO"), ("nivel","ALTO"), ("p80","NO-ALTO")],
        "acciones": ["disminuir_tonelaje", "disminuir_agua_cajon"],
        "duracion": 90,
        "prioridad": 1
    },
    {   # 4
        "id": 4,
        "descripcion": "Potencia Molino ALTO y NO-BAJANDO; Nivel ALTO; P80 ALTO",
        "si": [("pot_sag","ALTO"), ("pot_sag_tend","NO-BAJANDO"), ("nivel","ALTO"), ("p80","ALTO")],
        "acciones": ["disminuir_tonelaje"],
        "duracion": 90,
        "prioridad": 1
    },
]

# BLOQUE 2 — Cajón alto (5–7)
REGLAS["cajon_alto"] += [
    {   # 5
        "id": 5,
        "descripcion": "Nivel ALTO y NO-BAJANDO; Presión ALTO; P80 ALTO",
        "si": [("nivel","ALTO"), ("nivel_tend","NO-BAJANDO"), ("presion","ALTO"), ("p80","ALTO")],
        "acciones": ["disminuir_tonelaje"],
        "duracion": 90,
        "prioridad": 2
    },
    {   # 6
        "id": 6,
        "descripcion": "Nivel ALTO y NO-BAJANDO; Presión ALTO; P80 NO-ALTO",
        "si": [("nivel","ALTO"), ("nivel_tend","NO-BAJANDO"), ("presion","ALTO"), ("p80","NO-ALTO")],
        "acciones": ["disminuir_agua_cajon"],
        "duracion": 30,
        "prioridad": 2
    },
    {   # 7
        "id": 7,
        "descripcion": "Nivel ALTO y NO-BAJANDO; Presión NO-ALTO",
        "si": [("nivel","ALTO"), ("nivel_tend","NO-BAJANDO"), ("presion","NO-ALTO")],
        "acciones": ["aumentar_rpm_bomba"],
        "duracion": 30,
        "prioridad": 2
    },
]

# BLOQUE 3 — P80 alto (8–9)
REGLAS["p80_alto"] += [
    {   # 8
        "id": 8,
        "descripcion": "P80 ALTO y NO-BAJANDO; Presión NO-ALTO",
        "si": [("p80","ALTO"), ("p80_tend","NO-BAJANDO"), ("presion","NO-ALTO")],
        "acciones": ["aumentar_agua_cajon"],
        "duracion": 45,
        "prioridad": 3
    },
    {   # 9
        "id": 9,
        "descripcion": "P80 ALTO y NO-BAJANDO; Presión ALTO",
        "si": [("p80","ALTO"), ("p80_tend","NO-BAJANDO"), ("presion","ALTO")],
        "acciones": ["disminuir_tonelaje_suave", "disminuir_agua_molino"],
        "duracion": 90,
        "prioridad": 3
    },
]

# BLOQUE 4 — Optimizar potencia (10–12)(Revisar como implementar "En rango cerca de")
REGLAS["optimizar_potencia"] += [
    {   # 10
        "id": 10,
        "descripcion": "Potencia OK y SUBIENDO",
        "si": [("pot_sag","OK"), ("pot_sag_tend","SUBIENDO")],
        "acciones": ["disminuir_tonelaje"],
        "duracion": 90,
        "prioridad": 4
    },
    {   # 11
        "id": 11,
        "descripcion": "Potencia OK y ESTABLE (o varianza baja)",
        "si": [("pot_sag","OK"), ("pot_sag_tend","ESTABLE")],
        "acciones": ["mantener"],
        "duracion": 90,
        "prioridad": 4
    },
    {   # 12  (OR: Potencia BAJO o OK) y NO-SUBIENDO(Revisar regla que puede activar la 11)
        "id": 12,
        "descripcion": "Potencia BAJO u OK; y NO-SUBIENDO",
        "si": [
            {"OR": [("pot_sag","BAJO"), ("pot_sag","OK")]},
            ("pot_sag_tend","NO-SUBIENDO")
        ],
        "acciones": ["aumentar_tonelaje"],
        "duracion": 90,
        "prioridad": 4
    },
]

# BLOQUE 5 — P80 no alto (13)
REGLAS["p80_no_alto"] += [
    {
        "id": 13,
        "descripcion": "P80 BAJO u OK; y NO-SUBIENDO",
        "si": [
            {"OR": [("p80","BAJO"), ("p80","OK")]},
            ("p80_tend","NO-SUBIENDO")
        ],
        "acciones": ["disminuir_agua_cajon"],
        "duracion": 30,
        "prioridad": 5
    }
]

# BLOQUE 6 — Densidad / Presión (14–16)
REGLAS["densidad_presion"] += [
    {
        "id": 14,
        "descripcion": "Densidad ALTO y NO-BAJANDO; Presión NO-ALTO",
        "si": [("densidad","ALTO"), ("densidad_tend","NO-BAJANDO"), ("presion","NO-ALTO")],
        "acciones": ["aumentar_agua_cajon"],
        "duracion": 30,
        "prioridad": 6
    },
    {
        "id": 15,
        "descripcion": "Densidad ALTO y NO-BAJANDO; Presión ALTO",
        "si": [("densidad","ALTO"), ("densidad_tend","NO-BAJANDO"), ("presion","ALTO")],
        "acciones": ["disminuir_tonelaje"],
        "duracion": 90,
        "prioridad": 6
    },
    {
        "id": 16,
        "descripcion": "Densidad BAJO y NO-SUBIENDO (NO-Aumentando)",
        "si": [("densidad","BAJO"), ("densidad_tend","NO-SUBIENDO")],
        "acciones": ["disminuir_agua_cajon"],
        "duracion": 45,
        "prioridad": 6
    },
]

# BLOQUE 7 — Presión (17–18)
REGLAS["presion"] += [
    {
        "id": 17,
        "descripcion": "Presión ALTO y NO-BAJANDO",
        "si": [("presion","ALTO"), ("presion_tend","NO-BAJANDO")],
        "acciones": ["disminuir_rpm_bomba"],
        "duracion": 30,
        "prioridad": 7
    },
    {
        "id": 18,
        "descripcion": "Presión BAJO y NO-SUBIENDO",
        "si": [("presion","BAJO"), ("presion_tend","NO-SUBIENDO")],
        "acciones": ["aumentar_rpm_bomba"],
        "duracion": 30,
        "prioridad": 7
    },
]

"""#Fuerza de regla"""

def _norm_cond_text(s: str) -> str:
    """
    Normaliza textos de condiciones sin romper nombres con '_' como CERCA_ALTO.
    Acepta también variantes con '-' al momento de buscar en el diccionario pert.
    """
    if s is None:
        return ""
    return str(s).strip().upper()


def _mu_label(pert: dict, label: str) -> float:
    """
    Busca membresía en pert admitiendo variantes:
      - label tal cual
      - reemplazo '-' <-> '_'
    """
    if pert is None:
        return 0.0

    lab = _norm_cond_text(label)
    if lab in pert:
        return float(pert[lab])

    lab2 = lab.replace("-", "_")
    if lab2 in pert:
        return float(pert[lab2])

    lab3 = lab.replace("_", "-")
    if lab3 in pert:
        return float(pert[lab3])

    return 0.0


def mu_condicion(signal_fuzzy: dict, condicion) -> float:
    """
    Calcula μ(condición) dada una señal fuzzificada:
      signal_fuzzy = {"pert": {...}, "dom": ..., "val": ..., ...}

    Soporta:
      - "ALTO", "OK", "BAJO", "SUBIENDO", etc.
      - "NO-XXX" o "NO_XXX" (negación): 1 - μ(XXX)
    """
    pert = (signal_fuzzy or {}).get("pert", {}) or {}

    cond = _norm_cond_text(condicion)

    # negación
    if cond.startswith("NO-") or cond.startswith("NO_"):
        base = cond[3:]  # quita NO- / NO_
        mu_base = _mu_label(pert, base)
        return float(np.clip(1.0 - mu_base, 0.0, 1.0))

    return float(np.clip(_mu_label(pert, cond), 0.0, 1.0))


def fuerza_regla(result: dict, regla: dict, tnorm: str = "min") -> float:
    """
    Calcula la fuerza w de una regla usando:
      - AND con min (tnorm="min")
      - soporta cláusulas OR: {"OR":[(var,cond),(var,cond),...]}

    w = min( μ(cláusula_i) ) donde una cláusula OR vale max(...)
    """
    clauses = (regla or {}).get("si", []) or []
    if len(clauses) == 0:
        return 0.0

    mus = []

    for clause in clauses:
        # OR
        if isinstance(clause, dict) and "OR" in clause:
            m_or = 0.0
            for (var, cond) in clause["OR"]:
                if var not in result:
                    mu_v = 0.0
                else:
                    mu_v = mu_condicion(result[var], cond)
                m_or = max(m_or, float(mu_v))
            mus.append(float(m_or))
            continue

        # (var, cond)
        var, cond = clause
        if var not in result:
            mus.append(0.0)
        else:
            mus.append(float(mu_condicion(result[var], cond)))

    if not mus:
        return 0.0

    # AND: min (consistente con tu implementación original)
    if str(tnorm).lower() == "min":
        return float(min(mus))

    # fallback: también min
    return float(min(mus))

"""#Configuracion Esperas"""

# =============================================================================
# BLOQUE — FAMILIAS DE ESPERA (COOLDOWN) POR VARIABLE / SP
#
# IDEA
#   - El cooldown se guarda por "FAMILIA".
#   - Por defecto, la familia = el SP afectado por la acción (ACCION_A_SP[accion]).
#   - Así, todas las acciones que modifican el mismo SP comparten espera:
#       aumentar/disminuir + suave/normal => MISMA familia.
#
# CONFIGURACIÓN SIMPLE
#   1) Ajusta COOLDOWN_FAMILIA_S (segundos por SP/familia).
#   2) (Opcional) Si alguna acción debe ir a otra familia, usa ACCION_COOLDOWN_FAMILIA.
#   3) (Opcional) Si quieres duraciones específicas por acción, usa COOLDOWN_ACCION_S.
#
# PRIORIDAD PARA RESOLVER DURACIÓN (segundos):
#   A) COOLDOWN_ACCION_S[accion]                 (si existe)
#   B) COOLDOWN_FAMILIA_S[familia]              (familia por SP, o override)
#   C) regla['duracion'] dict: accion o familia
#   D) regla['duracion'] numérica
#   E) 0
# =============================================================================

# 1) Duración por familia (recomendado: familia = nombre del SP)
COOLDOWN_FAMILIA_S = {
    "sp_tonelaje": 180,
    "sp_agua_molino": 60,
    "sp_agua_cajon": 60,
    "sp_agua_ciclones": 60,
    "sp_rpm_bomba": 30,
}

# 2) (Opcional) Overrides de familia por acción (si necesitas excepciones)
#    Ejemplo: si quieres que cierto ajuste de agua use otra familia distinta al SP.
ACCION_COOLDOWN_FAMILIA = {
    # "aumentar_agua_molino_suave": "sp_agua_molino",  # normalmente no hace falta: ya cae por SP
}

# 3) (Opcional) Duraciones específicas por acción (si necesitas excepciones finas)
COOLDOWN_ACCION_S = {
    # "aumentar_tonelaje": 240,  # ejemplo: sobreescribe familia
}

def _cooldown_family(accion: str) -> str:
    """
    Devuelve la familia de cooldown para una acción.
    Prioridad:
      1) override explícito ACCION_COOLDOWN_FAMILIA
      2) SP asociado en ACCION_A_SP (familia por variable controlada)
      3) fallback: la acción misma (último recurso)
    """
    a = str(accion)

    if a in ACCION_COOLDOWN_FAMILIA:
        return str(ACCION_COOLDOWN_FAMILIA[a])

    sp = ACCION_A_SP.get(a, None)
    if sp is not None:
        return str(sp)

    return a

def cooldown_segundos_para_accion(accion: str, regla: dict) -> float:
    """
    Resuelve la duración de cooldown (s) para una acción considerando familias.
    """
    a = str(accion)
    fam = _cooldown_family(a)

    # A) por acción específica
    if a in COOLDOWN_ACCION_S:
        try:
            return float(COOLDOWN_ACCION_S[a])
        except Exception:
            return 0.0

    # B) por familia
    if fam in COOLDOWN_FAMILIA_S:
        try:
            return float(COOLDOWN_FAMILIA_S[fam])
        except Exception:
            return 0.0

    # C/D) desde la regla (si lo quieres por regla)
    dur = (regla or {}).get("duracion", 0)

    if isinstance(dur, dict):
        # por acción
        if a in dur:
            try:
                return float(dur[a])
            except Exception:
                return 0.0
        # por familia
        if fam in dur:
            try:
                return float(dur[fam])
            except Exception:
                return 0.0
        return 0.0

    try:
        return float(dur) if dur is not None else 0.0
    except Exception:
        return 0.0

"""#Motor de reglas con Esperas/Anti-SPAM"""

# =============================================================================
# BLOQUE — MOTOR DE REGLAS (COOLDOWN POR FAMILIA/SP + NO-OP)
# =============================================================================

def motor_reglas(
    result,
    REGLAS,
    tiempo_actual_s,
    cooldowns_accion,              # dict: familia -> t_exp
    alpha_min=0.05,
    alpha_cooldown=0.20,
    tnorm="min",
    ACCIONES_FISICAS=None,
):
    """
    Motor de reglas con esperas POR FAMILIA (por defecto: por SP).
    - cooldowns_accion guarda tiempos por familia: cooldowns_accion[familia] = t_exp
    - cualquier acción del mismo SP comparte cooldown.
    - acciones no-op (paso 0, ej 'mantener') NO aplican cooldown y pueden no mapear a SP.
    """

    if cooldowns_accion is None:
        cooldowns_accion = {}

    t_now = float(tiempo_actual_s)

    # ---------------------------------------------------------------------
    # 0) Limpieza: elimina cooldowns expirados (guardados por familia)
    # ---------------------------------------------------------------------
    for fam, t_exp in list(cooldowns_accion.items()):
        try:
            if t_now >= float(t_exp):
                cooldowns_accion.pop(fam, None)
        except Exception:
            cooldowns_accion.pop(fam, None)

    # ---------------------------------------------------------------------
    # 1) Mapa de pasos (ACCIONES_FISICAS) — robusto
    # ---------------------------------------------------------------------
    if ACCIONES_FISICAS is not None:
        pasos = ACCIONES_FISICAS
    else:
        pasos = globals().get("ACCIONES_FISICAS", {})

    if pasos is None:
        pasos = {}
    if not isinstance(pasos, dict):
        try:
            pasos = dict(pasos)
        except Exception:
            pasos = {}

    def _raw_paso(accion: str) -> float:
        try:
            return float(pasos.get(accion, np.nan))
        except Exception:
            return float("nan")

    def _es_noop(accion: str) -> bool:
        if accion in pasos:
            r = _raw_paso(accion)
            return np.isfinite(r) and (r == 0.0)
        return False

    def _accion_valida(accion: str) -> bool:
        # debe existir en ACCIONES_FISICAS
        if accion not in pasos:
            return False
        # no-op se acepta aunque no tenga SP
        if _es_noop(accion):
            return True
        # si no es no-op, debe mapear a SP
        return (ACCION_A_SP.get(accion) is not None)

    # ---------------------------------------------------------------------
    # 2) Construcción de candidatos
    # ---------------------------------------------------------------------
    cand = []
    for nombre_bloque, reglas in REGLAS.items():
        for regla in reglas:
            acciones = list((regla or {}).get("acciones", []) or [])

            # filtra acciones inválidas
            acciones = [a for a in acciones if _accion_valida(a)]
            if not acciones:
                continue

            # unique preserving order
            seen = set()
            acciones = [a for a in acciones if not (a in seen or seen.add(a))]

            # filtrar por cooldown (por familia)
            acciones_exec = []
            acciones_blocked = []

            for a in acciones:
                fam = _cooldown_family(a)
                t_exp = cooldowns_accion.get(fam, None)

                if t_exp is None:
                    acciones_exec.append(a)
                else:
                    try:
                        if t_now < float(t_exp):
                            acciones_blocked.append(a)
                        else:
                            acciones_exec.append(a)
                    except Exception:
                        acciones_exec.append(a)

            # si no queda nada ejecutable, descarta
            if not acciones_exec:
                continue

            w = float(fuerza_regla(result, regla, tnorm=tnorm))
            if w >= float(alpha_min):
                cand.append({
                    "prioridad": int(regla["prioridad"]),
                    "w": w,
                    "bloque": nombre_bloque,
                    "regla": regla,
                    "acciones_originales": acciones,
                    "acciones_ejecutables": acciones_exec,
                    "acciones_bloqueadas": acciones_blocked,
                })

    if not cand:
        return {
            "regla_activada": None,
            "bloque": None,
            "acciones": [],
            "acciones_originales": [],
            "acciones_bloqueadas": [],
            "descripcion": "",
            "duracion": 0,
            "duracion_regla_default": 0.0,
            "cooldown_hasta": None,
            "cooldowns_accion_hasta": {},      # acción -> t_exp (por familia)
            "duraciones_accion_s": {},         # acción -> duración aplicada (s)
            "prioridad": None,
            "alpha_max": 0.0,
            "belief": 0.0,
        }

    # ---------------------------------------------------------------------
    # 3) Selección por prioridad y w
    # ---------------------------------------------------------------------
    p_min = min(c["prioridad"] for c in cand)
    cand_p = [c for c in cand if c["prioridad"] == p_min]

    def _key_sel(c):
        rid = int(c["regla"]["id"])
        return (float(c["w"]), int(len(c["acciones_ejecutables"])), -rid)

    best = max(cand_p, key=_key_sel)

    regla_best = best["regla"]
    bloque_best = best["bloque"]
    w_best = float(best["w"])
    rid = int(regla_best["id"])

    acciones_originales = list(best["acciones_originales"])
    acciones_exec = list(best["acciones_ejecutables"])
    acciones_blocked = list(best["acciones_bloqueadas"])

    duracion_raw = (regla_best or {}).get("duracion", 0)
    dur_regla_default = 0.0
    if isinstance(duracion_raw, (int, float, np.number)):
        dur_regla_default = float(duracion_raw)

    # ---------------------------------------------------------------------
    # 4) Aplicar cooldown por familia (solo si w_best >= alpha_cooldown)
    # ---------------------------------------------------------------------
    duraciones_accion_s = {}
    if (w_best >= float(alpha_cooldown)):
        for a in acciones_exec:
            if _es_noop(a):
                continue

            dur_a = float(cooldown_segundos_para_accion(a, regla_best) or 0.0)
            duraciones_accion_s[a] = dur_a

            if dur_a > 0.0:
                fam = _cooldown_family(a)
                cooldowns_accion[fam] = float(t_now + dur_a)

    # logging: acción -> cooldown_hasta (resuelto por familia)
    cooldowns_accion_hasta = {}
    for a in acciones_originales:
        fam = _cooldown_family(a)
        cooldowns_accion_hasta[a] = cooldowns_accion.get(fam, None)

    # cooldown_hasta global: mínimo entre familias activas de acciones ejecutadas
    futuros = []
    for a in acciones_exec:
        fam = _cooldown_family(a)
        t_exp = cooldowns_accion.get(fam, None)
        if t_exp is not None:
            try:
                t_exp_f = float(t_exp)
                if t_exp_f > t_now:
                    futuros.append(t_exp_f)
            except Exception:
                pass
    cooldown_hasta = float(min(futuros)) if futuros else None

    return {
        "regla_activada": rid,
        "bloque": bloque_best,
        "acciones": acciones_exec,
        "acciones_originales": acciones_originales,
        "acciones_bloqueadas": acciones_blocked,
        "descripcion": (regla_best or {}).get("descripcion", ""),
        "duracion": duracion_raw,
        "duracion_regla_default": float(dur_regla_default),
        "cooldown_hasta": cooldown_hasta,
        "cooldowns_accion_hasta": cooldowns_accion_hasta,
        "duraciones_accion_s": duraciones_accion_s,
        "prioridad": int(regla_best["prioridad"]),
        "alpha_max": float(w_best),
        "belief": float(w_best),
    }

"""#Defuzzy"""

"""#Defuzzy (Sugeno basado en tabla belief)"""

ACCIONES_FISICAS = {
    "aumentar_tonelaje": 10,          # ton/h
    "disminuir_tonelaje": -10,        # ton/h
    "disminuir_tonelaje_suave": -5,   # ton/h

    "aumentar_agua_molino": 5,        # m3/h
    "disminuir_agua_molino": -5,      # m3/h
    "aumentar_agua_cajon": 4,         # m3/h
    "disminuir_agua_cajon": -4,       # m3/h
    "aumentar_agua_ciclones": 6,      # m3/h
    "disminuir_agua_ciclones": -6,    # m3/h

    "aumentar_rpm_bomba": 2,          # %
    "disminuir_rpm_bomba": -2,        # %

    "mantener": 0
}

ACCION_A_SP = {
    "aumentar_tonelaje": "sp_tonelaje",
    "disminuir_tonelaje": "sp_tonelaje",
    "disminuir_tonelaje_suave": "sp_tonelaje",

    "aumentar_agua_molino": "sp_agua_molino",
    "disminuir_agua_molino": "sp_agua_molino",

    "aumentar_agua_cajon": "sp_agua_cajon",
    "disminuir_agua_cajon": "sp_agua_cajon",

    "aumentar_agua_ciclones": "sp_agua_ciclones",
    "disminuir_agua_ciclones": "sp_agua_ciclones",

    "aumentar_rpm_bomba": "sp_rpm_bomba",
    "disminuir_rpm_bomba": "sp_rpm_bomba",

    "mantener": None
}

def _unidad_accion(accion):
    if "tonelaje" in accion:
        return "ton/h"
    if "agua" in accion:
        return "m3/h"
    if "rpm_bomba" in accion:
        return "%"
    return ""

def _modo_desde_accion(accion: str) -> str:
    """
    Inferencia desde nombre (tal como pediste):
      - aumentar_*  => inc_rap
      - disminuir_* => dec_rap
      - *_suave     => inc / dec (según signo)
      - mantener    => inc (pero delta 0)
    """
    a = str(accion).lower().strip()
    if a == "mantener":
        return "inc"

    suave = ("_suave" in a)

    if a.startswith("aumentar"):
        return "inc" if suave else "inc_rap"
    if a.startswith("disminuir"):
        return "dec" if suave else "dec_rap"
    # fallback conservador
    return "inc"

def scale_tabla(belief: float, modo: str) -> float:
    """
    Tabla solicitada (normalizada a [0,1]):
      Belief 1   => inc_rap=1.0, inc=1.0, dec=1.0, dec_rap=1.0
      Belief 0.5 => inc_rap=0.5 (25/50), inc=0.4 (10/25), dec=0.4, dec_rap=0.5
      Belief 0   => 0

    En la práctica: delta = sign * scale * max_step
    """
    b = float(np.clip(belief, 0.0, 1.0))
    m = str(modo).lower()

    # ratios en 0.5
    r05 = 0.5 if m in ("inc_rap", "dec_rap") else 0.4
    return float(np.interp(b, [0.0, 0.5, 1.0], [0.0, r05, 1.0]))

def defuzzy_sugeno(result, salida_motor, ACCIONES_FISICAS=ACCIONES_FISICAS):
    """
    Sugeno: belief = fuerza de regla (salida_motor['belief'])
    Para cada acción:
      z = sign * scale_tabla(belief, modo) * |max_step|
    Retorna lista de comandos (uno por acción).

    Cambio clave:
      - Si la acción es no-op (raw == 0), NO genera comando.
      - Esto permite que "mantener" exista como acción semántica sin SP asociado.
    """
    rid = salida_motor.get("regla_activada")
    if rid is None:
        return []

    belief = float(salida_motor.get("belief", 0.0))
    acciones = salida_motor.get("acciones", []) or []

    comandos = []
    for accion in acciones:
        if accion not in ACCIONES_FISICAS:
            continue

        raw = float(ACCIONES_FISICAS[accion])

        # no-op => no emitir comando (incluye "mantener": 0)
        if raw == 0.0:
            continue

        sp_col = ACCION_A_SP.get(accion)
        if sp_col is None:
            # si no hay SP asociado y además no es no-op (ya filtrado), es inconsistencia
            continue

        max_step = abs(raw)
        signo = 1.0 if raw > 0 else (-1.0 if raw < 0 else 0.0)

        modo = _modo_desde_accion(accion)
        sc = float(scale_tabla(belief, modo))
        delta = float(signo * sc * max_step)

        comandos.append({
            "accion": accion,
            "sp_col": sp_col,
            "unidad": _unidad_accion(accion),
            "belief": belief,
            "modo": modo,
            "scale": sc,
            "max_step": max_step,
            "delta_sp": delta
        })

    return comandos

"""#Procesador"""

def crear_procesador_rt(time_col=None, dt_s=60.0):
    estado = {
        "last_time": None,
        "last_len": 0,
        "hist_pend": {},
        "cooldowns_accion": {},   # <- ahora por acción
        "sp_state": {}
    }

    req = [
        "pot_bolas","lmin_bolas",
        "pot_sag","lmax_sag",
        "nivel","lmin_nivel","lmax_nivel",
        "p80","lmax_p80",
        "presion","lmax_pres",
        "densidad","lmax_dens"
    ]

    def _to_seconds(ts):
        t = pd.to_datetime(ts, errors="coerce")
        if pd.isna(t):
            return np.nan
        return t.value / 1e9

    def _get_tiempo(row):
        if time_col is not None and time_col in row:
            t = _to_seconds(row[time_col])
            if np.isfinite(t):
                return float(t)
        if estado["last_time"] is None:
            estado["last_time"] = 0.0
        return float(estado["last_time"] + dt_s)

    def _leer_sp(variables):
        for sp in ["sp_tonelaje","sp_agua_molino","sp_agua_cajon","sp_agua_ciclones","sp_rpm_bomba"]:
            v = variables.get(sp, np.nan)
            if np.isfinite(v):
                estado["sp_state"][sp] = float(v)
            else:
                estado["sp_state"].setdefault(sp, 0.0)

    def _aplicar_comandos(comandos):
        for c in comandos:
            sp = c["sp_col"]
            delta = float(c["delta_sp"])
            estado["sp_state"][sp] = float(estado["sp_state"].get(sp, 0.0) + delta)

    def procesar(df_in):
        if df_in is None or len(df_in) == 0:
            return pd.DataFrame()

        df = df_in.copy()

        for c in req:
            if c not in df.columns:
                raise ValueError(f"Falta columna requerida: {c}")

        # nuevas filas
        if time_col is None or time_col not in df.columns:
            if len(df) > estado["last_len"]:
                df_new = df.iloc[estado["last_len"]:].copy()
            else:
                df_new = df.copy()
        else:
            df["_t_s"] = df[time_col].apply(_to_seconds)
            if estado["last_time"] is None:
                df_new = df.copy()
            else:
                df_new = df[df["_t_s"] > estado["last_time"]].copy()
            df_new = df_new.sort_values("_t_s")

        if len(df_new) == 0:
            return pd.DataFrame()

        out_rows = []

        for _, row in df_new.iterrows():
            variables = row.to_dict()
            t_s = float(_get_tiempo(row))

            _leer_sp(variables)

            # fuzzy estado
            result = evaluar_fuzzy(
                pv_bolas=variables["pot_bolas"], lmin_bolas=variables["lmin_bolas"],
                pv_sag=variables["pot_sag"],     lmax_sag=variables["lmax_sag"],
                pv_nivel=variables["nivel"],     lmin_nivel=variables["lmin_nivel"], lmax_nivel=variables["lmax_nivel"],
                pv_p80=variables["p80"],         lmax_p80=variables["lmax_p80"],
                pv_pres=variables["presion"],    lmax_pres=variables["lmax_pres"],
                pv_dens=variables["densidad"],   lmax_dens=variables["lmax_dens"]
            )

            # fuzzy tendencia
            hist = estado["hist_pend"]
            result["pot_bolas_tend"] = evaluar_pendiente_var("pot_bolas", variables["pot_bolas"], t_s, hist)
            result["pot_sag_tend"]   = evaluar_pendiente_var("pot_sag",   variables["pot_sag"],   t_s, hist)
            result["nivel_tend"]     = evaluar_pendiente_var("nivel",     variables["nivel"],     t_s, hist)
            result["p80_tend"]       = evaluar_pendiente_var("p80",       variables["p80"],       t_s, hist)
            result["presion_tend"]   = evaluar_pendiente_var("presion",   variables["presion"],   t_s, hist)
            result["densidad_tend"]  = evaluar_pendiente_var("densidad",  variables["densidad"],  t_s, hist)

            # motor (cooldown por acción)
            salida_motor = motor_reglas(
                result, REGLAS, t_s, estado["cooldowns_accion"],
                ACCIONES_FISICAS=ACCIONES_FISICAS,
                alpha_min=0.05, alpha_cooldown=0, tnorm="min"
            )

            # defuzzy
            comandos = defuzzy_sugeno(result, salida_motor, ACCIONES_FISICAS=ACCIONES_FISICAS)

            # aplicar comandos
            _aplicar_comandos(comandos)

            # -------------------------
            # logging
            # -------------------------
            flat = {"t_s": t_s}

            for var, d in result.items():
                flat[f"{var}_dom"] = d.get("dom")
                flat[f"{var}_val"] = float(d.get("val", np.nan))
                flat[f"{var}_offset"] = float(d.get("offset", np.nan))
                pert = d.get("pert", {}) or {}

                if any(k in pert for k in ["BAJO","OK","ALTO"]):
                    flat[f"{var}_mu_BAJO"] = float(pert.get("BAJO", np.nan))
                    flat[f"{var}_mu_OK"]   = float(pert.get("OK", np.nan))
                    flat[f"{var}_mu_ALTO"] = float(pert.get("ALTO", np.nan))

                if any(k in pert for k in ["SUBIENDO","ESTABLE","BAJANDO"]):
                    flat[f"{var}_mu_SUBIENDO"] = float(pert.get("SUBIENDO", np.nan))
                    flat[f"{var}_mu_ESTABLE"]  = float(pert.get("ESTABLE", np.nan))
                    flat[f"{var}_mu_BAJANDO"]  = float(pert.get("BAJANDO", np.nan))

            flat["regla_activada"] = salida_motor.get("regla_activada")
            flat["bloque"] = salida_motor.get("bloque")
            flat["descripcion_regla"] = salida_motor.get("descripcion")

            # compat: duracion original (num o dict) + default numérico si existía
            flat["duracion_regla"] = salida_motor.get("duracion")
            flat["duracion_regla_default"] = float(salida_motor.get("duracion_regla_default", 0.0))

            flat["alpha_max"] = float(salida_motor.get("alpha_max", 0.0))
            flat["belief"] = float(salida_motor.get("belief", 0.0))

            flat["acciones_regla"] = str(salida_motor.get("acciones_originales", []))
            flat["acciones_ejecutables"] = str(salida_motor.get("acciones", []))
            flat["acciones_bloqueadas"] = str(salida_motor.get("acciones_bloqueadas", []))

            # nuevo: duraciones por acción aplicadas + cooldowns por acción
            flat["duraciones_accion_s"] = str(salida_motor.get("duraciones_accion_s", {}))
            flat["cooldowns_accion_hasta"] = str(salida_motor.get("cooldowns_accion_hasta", {}))
            flat["cooldown_hasta"] = salida_motor.get("cooldown_hasta")

            flat["n_comandos"] = len(comandos)
            flat["comandos"] = str(comandos)

            for sp_col, sp_val in estado["sp_state"].items():
                flat[sp_col] = float(sp_val)

            out_rows.append(flat)
            estado["last_time"] = t_s

        if time_col is None or time_col not in df_in.columns:
            estado["last_len"] = max(estado["last_len"], len(df_in))

        df_out = pd.concat([df_new.reset_index(drop=True), pd.DataFrame(out_rows)], axis=1)
        return df_out

    return procesar